### ISSUE TITLE
packer 0.8.2 and file/folder upload

### ISSUE THREAD

**Issue by jamesyouknowwho** [MSOpenTech/packer-azure#100]
I'm having a problem with uploading a file or folder with Packer 0.8.2.  I see that files and folder upload are supported [here] (https://github.com/MSOpenTech/packer-azure/blob/master/packer/communicator/azureVmCustomScriptExtension/communicator.go#L365) but not having much luck.  I'm looking at this [example] (https://github.com/MSOpenTech/packer-azure/blob/master/config_examples/packer-azure_Win2012r2.json#L25)

Here is the error with PACKER_LOG=1 when just pointing to a single file.  The results are the same when pointing to a folder as in the example above.

[log] (https://gist.github.com/jamesyouknowwho/e597b5e68e766e0df674)

Any ideas on how to troubleshoot?
Thanks,
Paul

**Comment by paulmey** [comment]
Setting the environment variable `PACKER_LOG_AZURE_MAXLEN` to `1000` will log the actual HTTP requests going to Azure up to the first 1000 characters. However, I'm not sure if this also works for the storage requests.
I'll run the examples and see if I can repro the problem.

**Comment by paulmey** [comment]
moving discussion to #107
