### ISSUE TITLE
Error while removing temporary service

### ISSUE THREAD

**Issue by michel3** [MSOpenTech/packer-azure#106]
When trying to create an image, the builder fails when it tries to cleanup. Logging of error:

==> azure: Removing temporary Azure service and its deployments, if any...
2015/10/05 10:45:23 packer-builder-azure: 2015/10/05 10:45:23 [AZURE] DELETE services/hostedservices/PkrSrvqglgl303y9?comp=media
2015/10/05 10:45:23 packer-builder-azure: 2015/10/05 10:45:23 [AZURE] <<< operation id: abfcbe8176a21a83b7289de37cc0b177
2015/10/05 10:45:23 packer-builder-azure: 2015/10/05 10:45:23 [AZURE] WaitForOperation( abfcbe8176a21a83b7289de37cc0b177 ) - begin
2015/10/05 10:45:55 packer-builder-azure: 2015/10/05 10:45:55 [AZURE] WaitForOperation( abfcbe8176a21a83b7289de37cc0b177 ) - end, duration: 32.090532312s, err: <nil>
2015/10/05 10:45:55 ui error: __Build 'azure' errored: Error creating page blob of size 2022 in container packer-provision-qglgl303y9 for file provision-d75ead8f-9daf-4398-8f40-7c6d82dcab81.ps1: storage: service returned error: StatusCode=400, ErrorCode=InvalidHeaderValue, ErrorMessage=The value for one of the HTTP headers is not in the correct format.__
RequestId:1de8cfdc-0001-00d7-2c4a-ff84c9000000
Time:2015-10-05T08:45:21.8041791Z, RequestId=1de8cfdc-0001-00d7-2c4a-ff84c9000000
2015/10/05 10:45:55 Builds completed. Waiting on interrupt barrier...

**Comment by jamesyouknowwho** [comment]
Same error as [#100] (https://github.com/MSOpenTech/packer-azure/issues/100).  I tried PACKER_LOG_AZURE_MAXLEN to 1000 but nothing useful that I could see. Haven't had time to debug.

**Comment by paulmey** [comment]
moving the discussion to #107
