### ISSUE TITLE
Workflow consideration - attach VHD as disk, but don't boot

### ISSUE THREAD

**Issue by Iristyle** [MSOpenTech/packer-azure#11]
As I understand the current workflow:

* Acquire an image
* Boot it
* Modify it during the provisioning sequence
* Publish it

There's an additional workflow for building Linux VMs that would be useful to enable:

* Acquire an image
* Mount it as a disk (using the same OS for the host as for the VHD that is mounted)
* Modify the contents of the mounted disk, but not the host OS
* Detach disk
* Publish the attached disk that was modified

Thoughts on enabling this scenario?

It can likely be implemented using a round-about set of scripts in the provisioning step, but seems like it would be nice to have as a first-class facility in the workflow.

**Comment by paulmey** [comment]
I'm not sure that Packer supports or promotes this workflow for other platforms.
Also, AFAIK, Azure currently does not have an API to get a copy of an OS image from its image repository. So acquiring an image without booting it may be impossible.

**Comment by paulmey** [comment]
Since there is no way to get to an OS image from the image repository directly for mounting it, I'm closing this issue.
