### ISSUE TITLE
Timeout waiting for SSH

### ISSUE THREAD

**Issue by carldurrant** [MSOpenTech/packer-azure#112]
Hi, 

I'm having the timeout waiting for SSH issue with the following configuration: 

Ubuntu 14.04 deployed in Azure
Packer v0.8.6
Azure-packer - latest pull from Git

Please can you help?

**Comment by carldurrant** [comment]
Some further info: the environment I'm working in has Azure ExpressRoute configured to route all traffic back internally. I've used the VNet and subnet configuration options to add the temporary VM that is  created to a connected VNet/subnet, and while Packer is waiting for SSH I can SSH into the VM using the internal address but not the VIP

**Comment by paulmey** [comment]
Yeah, we need to add a config flag to go to the private IP instead of the VIP.

**Comment by carldurrant** [comment]
That makes sense, I specified the configuration to add the internal VNet and subnet but couldn't see how to make it use them instead of the VIP. I have managed to work around the issue by making the VIP routable internally with a user defined route. Thanks

**Comment by paulmey** [comment]
Clever!
