### ISSUE TITLE
Builder failing waiting for RPC

### ISSUE THREAD

**Issue by anthony-7** [MSOpenTech/packer-azure#27]
Hi all, can anyone suggest what I need to do to get past this problem...

Waiting for RPC address for: C:\Program Files (x86)\Packer\packer-builder-azure.exe
ui error: Failed to create build 'azure': 
timeout while waiting for plugin to start

I'm using Packer v0.7.5 and this is my builder...

  "builders": [{
    "type": "azure",
    "subscription_name": "My Trial",
    "storage_account" : "portalvhds466j4jxxxxxxx",
	 "os_type"	: "Windows",
    "os_image_label"	: "3a50f22b388a4ff7ab41029918570fa6__Windows-Server-2012-Essentials-20131217-enus",
    "location"	: "Australia Southeast",
    "instance_size" : "Medium",
    "user_image_label" : "FirstAttempt-0112-0438"
  }],

**Comment by v-vlshch** [comment]
What client OS do you use? Did you try the plugin on another devbox?

**Comment by anthony-7** [comment]
I'm on Windows 8.1.

I haven't tried another devbox. I'll try and set one up.

**Comment by anthony-7** [comment]
The other developer does not have this issue on his Windows 8.1 64 bit. I didn't mention in the previous post...my Windows 8 system is also 64 bit.

**Comment by v-vlshch** [comment]
It may be a security policy issue. Did you download packer-builder-azure.exe from github?

**Comment by anthony-7** [comment]
Your right...it is a security issue. Comodo was sandboxing the execution of the builder exe as it saw Packer files as "Unrecognised Files". To fix this, you can mark the Packer files as Trusted or turn off Sandboxing.

Thanks for your help.

PS. Yes, I did download the builder exe from github.
