### ISSUE TITLE
Public Port specification on Endpoints

### ISSUE THREAD

**Issue by anthony-7** [MSOpenTech/packer-azure#29]
Would it be possible to add a parameter to the builder that specifies the Public Port for the Remote Desktop endpoint for the temporary VM instance.

Since the allocated Public Port is random, the Azure Plugin is failing because WinRM can't get through our company firewall. Our Sys Admin has given my machine temporary access through the firewall but this is not ideal.

**Comment by sepiroth887** [comment]
Bump and adding support to specify VNets would be awesome. Or is this already possible?

**Comment by paulmey** [comment]
Hi @anthony-7 ,
Are you referring to port 5986?
I noticed that the rest api builder did not even allocate ports for Windows machines. I'm preparing a PR that will add 5986 and 3389 with default mappings for Windows and port 22 for Linux.

@sepiroth887 : I saw your PR. Now that we're removed the powershell based builder, I'll see if I can still merge it.

Thanks, Paul

**Comment by anthony-7** [comment]
Hi Paul,

yes, I was referring to port 3389. 5986 would be good also.

Anthony.

**Comment by saturnlevrai** [comment]
It is possibile to specify endpoints in packer json builder ?

**Comment by paulmey** [comment]
@saturnlevrai not currently. What's the scenario?
