### ISSUE TITLE
 Error Stopping Temporary Azure VM: Remote server returned error

### ISSUE THREAD

**Issue by diddek** [MSOpenTech/packer-azure#35]
Hi,

Trying to build an azure image with the following conf:

{
"builders":[{
  "type": "azure",
  "publish_settings_path":  "azure/Free Trial-1-27-2015-credentials.publishsettings",
  "subscription_name":  "Free Trial",
  "storage_account":  "xxx",
  "storage_account_container":  "yyy",
  "os_type":  "Linux",
  "os_image_label": "Ubuntu Server 14.04 LTS",
  "location": "West Europe",
  "instance_size":  "Small",
  "user_image_label": "usp-174-apache24-ubuntu1404-amd64"
}],
"provisioners":[{}]

Everything goes well until the end:

azure: Error Stopping Temporary Azure VM: Remote server returned error: 'The server encountered an internal error. Please retry the request.' (10 times).

No further log.

What am I doing wrong?

Kind regards,

Dirk

**Comment by paulmey** [comment]
You're probably doing nothing wrong, but this says that the Azure API encountered an error when packer-azure tried to stop the temporary VM.  This can be a transient problem in the Azure API (hence the "Please retry the request"), so packer-azure retries the same request up to 10 times. In this case, it kept failing and packer-azure gave up.
If you run into this consistently or want to help us debug these kinds of situations, it would be helpful to enable debug logging and provide the relevant part of the log here. You can enable debug logging by setting the environment variables `PACKER_LOG=yes` and `PACKER_LOG_PATH=debug_log_file.log`. See https://packer.io/docs/other/debugging.html for more information on debug logging.

**Comment by diddek** [comment]
Hi Paul,

Thanks - I will retry here and follow up on the ticket.

Kind regards,

Dirk

**Comment by diddek** [comment]
Hi Paul,

Now for some reason it does work.

Thanks for the plugin!

Kind regards,

Dirk
