### ISSUE TITLE
Provide support for MacOS X

### ISSUE THREAD

**Issue by mfdii** [MSOpenTech/packer-azure#44]
I was able to get this to build using the instructions for linux. On running a build I got an error that the cert.pem file doesn't exist. 

I traced it to this section:

https://github.com/MSOpenTech/packer-azure/blob/master/packer/builder/azure/driver_restapi/request/subcriptionManagement.go#L199

I think if you simply added an OR to the statement looking for OSX, everything else should work. I was able to generate the pem file manually using the command you run and then the builds were successful after that. 

I will try to send you a PR.

**Comment by paulmey** [comment]
:+1: Cool, looking forward to that PR. LMK if you need help!

**Comment by paulmey** [comment]
Closed with #45
