### ISSUE TITLE
Long running extensionSettings time out, even if they are still running on the host

### ISSUE THREAD

**Issue by nathansoz** [MSOpenTech/packer-azure#52]
I'm using packer to provision a machine that installs a large program during the provisioning state (Visual Studio Community). It looks like the timeout is 20 minutes due to a hard-coded limit on the polling loop.

It would be cool if (https://github.com/MSOpenTech/packer-azure/blob/master/packer/communicator/azureVmCustomScriptExtension/communicator.go#L200) could be set as an optional parameter in the json file. Perhaps also changing the sleep time from 40seconds -> 60seconds would be helpful, because then the parameter could be called something like "Timeout Minutes."

I'm willing to write a pull request if you think this is a good idea. I may fork and write it for my own personal use anyways.

**Comment by paulmey** [comment]
Good suggestion, we'll gladly take a PR for that. It's been on my backlog but I haven't had the need for it yet.

**Comment by nathansoz** [comment]
Great. I'll take a look and see what I can do soon.

**Comment by nathansoz** [comment]
So I was looking at the packer shell provisioner a bit closer to see what they do with shell command timeouts. It doesn't appear that they have a timeout that the user can configure... in fact, it doesn't look like they have a timeout at all. I don't have much experience with go, but it looks like they are just waiting for the cmd routine to complete in the code below.

https://github.com/mitchellh/packer/blob/master/provisioner/shell/provisioner.go#L259

So I wonder if there is a good reason to have a timeout in the first place? Thoughts?

**Comment by paulmey** [comment]
I like the idea of a configurable timeout. Especially if there is also an option to disable the timeout completely.
We use packer in our automated build of images and it's nice if packer cleans up whatever it created when a build fails because something is taking way more time than expected.

I vote for the configurable timeout option.
