### ISSUE TITLE
OpenLogic images do not support SSH access

### ISSUE THREAD

**Issue by ldanielw1** [MSOpenTech/packer-azure#62]
I started trying to build centOS images from packer-azure, and it's going great. Everything gets saved properly. However, when I try to create a new viritual machine from the the created image, even if I only give it a password for SSH authentication, I get denied from logging in on the basis of:
    Permission denied (publickey,gssapi-keyex,gssapi-with-mic).

Is this a packer-azure issue? Or should I just close this issue, and talk to Microsoft Azure about this?

**Comment by paulmey** [comment]
The previous maintainer made a note about this here: https://github.com/MSOpenTech/packer-azure#known-issues
I'm not sure what the status of this issue is or if it's fixable. I can certainly (help to) look into it...

**Comment by paulmey** [comment]
@ldanielw1 did you find that this issue still exists when building CentOS images?

**Comment by ldanielw1** [comment]
Yes, this bug still exists.

**Comment by paulmey** [comment]
Thanks for confirming!

**Comment by tomconte** [comment]
Hi there! I am hitting this issue too. Is there a fix or workaround? Thanks!

**Comment by tomconte** [comment]
I think the problem might be in `CreateVirtualMachineDeployment.go` ? Not sure why it wouldn't affect Ubuntu VM's too ... 

```
buff.WriteString("<DisableSshPasswordAuthentication>true</DisableSshPasswordAuthentication>")
```

**Comment by paulmey** [comment]
Hi @tomconte 
AFAIK, the azure agent is supposed to handle the value of DisableSshPasswordAuthentication in the VM deployment xml and configure SSH daemon accordingly. It may have a bug there for the case of CentOS...?
Also not sure if waagent --deprov is supposed to clean that up...

**Comment by paulmey** [comment]
Ok, I looked it up... The Azure agent only takes action if it needs to disable password auth:
https://github.com/Azure/WALinuxAgent/blob/ddfe7821580842f6f2de1a9ee2c68629bd26a5bf/waagent#L4441-L4447
So there is no way to undo this. I'll change the code to not disable password auth because it can't be undone by a re-deploy.
