### ISSUE TITLE
Where do you get publishprofile?

### ISSUE THREAD

**Issue by cloudnautique** [MSOpenTech/packer-azure#65]
Hello, I have been searching everywhere, and can not find where to get the publish profile. I'm anxious to try this project out!

Thanks for the help

**Comment by paulmey** [comment]
https://manage.windowsazure.com/publishsettings will give you a publish profile for all of your azure subscriptions. It's also mentioned [here](https://github.com/MSOpenTech/packer-azure#linux-dev-box) as http://go.microsoft.com/fwlink/?LinkId=254432 (which forwards there).

**Comment by cloudnautique** [comment]
Thanks, for whatever reason I could only find the one labeled dead link.
