### ISSUE TITLE
Enable adding data disks

### ISSUE THREAD

**Issue by ghost** [MSOpenTech/packer-azure#66]
From https://github.com/MSOpenTech/azure-sdk-for-go/blob/master/management/vmutils/datadisks.go#L11 there's a function to add a data disk to a VM. Could this functionality be added to packer-azure?

**Comment by paulmey** [comment]
Sounds like a good feature. We'll need #57 to merge first...

**Comment by camechis** [comment]
This would be very helpful.  I need the ability to add extra disks to my VMs.  This is kind of a show stopper.

**Comment by paulmey** [comment]
@ghost @camechis : do you need 'new'/'empty' data disks, already existing vhd's, or a mix?

**Comment by camechis** [comment]
@paulmey I am thinking new/empty.  My use case is I need to provision the vms that can be used for some type of NoSQL store.  With the default vms I need to mount a disk ( eg. /var ) that can have large amounts of storage.

**Comment by paulmey** [comment]
See if #91 gets the show going for y'all. I can see if I can maybe add an option to specify things like host caching type if you need that?

**Comment by camechis** [comment]
#91 I believe gets us there.
