### ISSUE TITLE
azure vm show <vmname> - does not show user created vm's, only public?

### ISSUE THREAD

**Issue by sc0ttruss** [MSOpenTech/packer-azure#68]
Hi,
          I noticed I can see user created vm's through the web portal, but not via the command line.  Any ideas on how to get them to show up?  

eg, I can see the image, but 

 azure vm show PackerMade_Ubuntu_Serv14_2015-May-1_16-29
 info:    Executing command vm show
 + Getting virtual machines                                                     
 warn:    No VMs found
 info:    vm show command OK

 vm image list 
 data:    PackerMade_Ubuntu_Serv14_2015-May-1_16-29                                                                                         User      Linux

**Comment by paulmey** [comment]
Hi @sc0ttruss,

packer-azure removes the running VM (after generalizing it) and leaves you with a VM image. If you want to have a running instance, you have to create a VM based on that image.

Does that answer your question?

Thanks, Paul

**Comment by paulmey** [comment]
Hi @sc0ttruss, were you able to find the image?
