### ISSUE TITLE
errors installing driver_restapi

### ISSUE THREAD

**Issue by mattiasr** [MSOpenTech/packer-azure#72]
go get github.com/MSOpenTech/packer-azure/packer/builder/azure/driver_restapi

# github.com/MSOpenTech/packer-azure/packer/builder/azure/driver_restapi
../../MSOpenTech/packer-azure/packer/builder/azure/driver_restapi/builder.go:44: undefined: packer.ConfigTemplate

I have tried with binary packer 0.7.2 and 0.7.5, compiled dev version (0.7.5) and still get the same error.
Also tried golang 1.3 and 1.4

Using CentOS 7, will all updates as of 8/6

really need to get this working since we working to get our product into Azure via packer.

**Comment by mattiasr** [comment]
i used developer version of packer code, as of 

commit 1d3a4d6aa2b2c969bb52f00e27113d21a28ad793
Author: Mitchell Hashimoto <mitchell.hashimoto@gmail.com>
Date:   Wed May 27 17:56:45 2015 -0700

    packer: remove ConfigTemplate

They removed the loads of stuff, i got it to build when i checked out v0.7.5 tag and built.

**Comment by paulmey** [comment]
yep, I noticed the same, working on a fix
