### ISSUE TITLE
Racy pemfile creation causes errors for parallel builds

### ISSUE THREAD

**Issue by bellkev** [MSOpenTech/packer-azure#76]
I'm consistently getting errors when trying to build two images in parallel with the same subscription. It looks like the first build enters [this if block](https://github.com/MSOpenTech/packer-azure/blob/3cb56d474c7481ba4f7ca265f7afea734c37242c/packer/builder/azure/driver_restapi/request/SubscriptionManagement.go#L168-223) and writes the tag file, then the next build sees the tagfile and immediately tries to read the pemfile, even though it hasn't finished being written yet.

This results in an error like this:
```
Build 'XXXX' errored: Error creating request manager: Failed to Parse PublishSettings: open /home/ubuntu/.packer_azure/XXXX/cert.pem: no such file or directory
```

**Comment by paulmey** [comment]
I was planning to not create the files completely and write the keys/certs out in the debug logs only. Would that suit your needs?

**Comment by bellkev** [comment]
Anything that removes the critical period between writing the "tagfile" and writing the "pemfile" where another thread calling ParsePublishSettings will fail for the same subscription id (I haven't confirmed _super_ thoroughly that that's the issue I'm seeing, but I'm pretty sure it is based on my read of the logs/code), should be fine. It sounds like a scheme where the pemfile isn't written at all should certainly solve it :smiley:

**Comment by paulmey** [comment]
Take a look at #80 and see if that would fix your issue. Note that in between, we switched from having our own HTTP client to using the [azure-sdk-for-go](http://github.com/Azure/azure-sdk-for-go) so much of the tagfile stuff is gone also.

**Comment by bellkev** [comment]
I've been using the binary release, so once that includes #80 I'll try it out. Thanks!

**Comment by paulmey** [comment]
I moved the prerelease tag to the head of master. When Travis finishes, the binaries should show up here: https://github.com/MSOpenTech/packer-azure/releases/tag/prerelease
